Document: meet-accountmanager
Title: Debian meet-accountmanager Manual
Author: <insert document author here>
Abstract: This manual describes what meet-accountmanager is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/meet-accountmanager/meet-accountmanager.sgml.gz

Format: postscript
Files: /usr/share/doc/meet-accountmanager/meet-accountmanager.ps.gz

Format: text
Files: /usr/share/doc/meet-accountmanager/meet-accountmanager.text.gz

Format: HTML
Index: /usr/share/doc/meet-accountmanager/html/index.html
Files: /usr/share/doc/meet-accountmanager/html/*.html
